version: '3.8'

services:
  postgres:
    image: postgres:17.5
    container_name: postgresdb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mygame
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: redisdb
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      - postgres
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    command: >
      -url=jdbc:postgresql://postgres:5432/mygame
      -user=root
      -password=example
      migrate

volumes:
  postgres-data:
  redis-data:
